{% set name = "orange-spectroscopy" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 82de5c8d4f4a1fc94c80f308e5c84ada332d133e0da1272805fc050c8bc6665f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - recommonmark
    - pip
  run:
    - python >={{ python_min }}
    - setuptools >=51.0.0
    - pip >=19.3
    - numpy >=1.21.0,<2.0.0
    - orange3 >=3.37.0
    - orange-canvas-core >=0.2.0
    - orange-widget-base >=4.23.0
    - scipy >=1.9.0
    - scikit-learn >=1.3.0
    - spectral >=0.22.3,!=0.23
    - serverfiles >=0.2
    - anyqt >=0.2.0
    - pyqtgraph >=0.13.1
    - colorcet
    - h5py
    - extranormal3 >=0.0.3
    - renishaw_wire >=0.1.8
    - pillow >=9.0.0
    - lmfit >=1.3.2
    - bottleneck
    - pebble
    - agilent-format >=0.4.5

test:
  imports:
    - orangecontrib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - xgboost =2.0.3 #last one known as supported, job 20240702.2

about:
  home: https://github.com/Quasars/orange-spectroscopy
  summary: Extends Orange to handle spectral and hyperspectral analysis.
  license: Unlicense
  license_file: LICENSE
  description: Orange add-on for spectral data analysis. Provides spectra and hyperspectra plotting, interpolation, preprocessing (cutting, smoothing, normalization), and integration. Supports common spectral file formats.
  dev_url: https://github.com/Quasars/orange-spectroscopy
  doc_url: https://orange-spectroscopy.readthedocs.io/

extra:
  recipe-maintainers:
    - HeavyTony2
